authing:
  userpool:
    id: 5f8eb6f27371b7d5ab760831
    secret: 6aeb8f798f7b8f7aa584849a158253be
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/zhifou?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Hongkong&characterEncoding=utf-8
    username: qianlei
    password: 123456
#logging:
#  level:
#    root: debug