apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: zhifou
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /elasticsearch
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: zhifou
  name: elasticsearch
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: zhifou
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: install-plugins
          image: elasticsearch:7.6.2
          command:
            - bash
            - -c
            - |
              curl -LJO https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.6.2/elasticsearch-analysis-ik-7.6.2.zip
              unzip -d plugins/ik elasticsearch-analysis-ik-7.6.2.zip
          volumeMounts:
            - name: plugins
              mountPath: /usr/share/elasticsearch/plugins/
      containers:
        - name: elasticsearch
          image: elasticsearch:7.6.2
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
          volumeMounts:
            - name: plugins
              mountPath: /usr/share/elasticsearch/plugins/
            - name: data
              mountPath: /usr/share/elasticsearch/data/
            - name: localtime
              readOnly: true
              mountPath: /etc/localtime
      volumes:
        - name: plugins
          emptyDir: { }
        - name: data
          persistentVolumeClaim:
            claimName: elasticsearch
        - name: localtime
          hostPath:
            type: File
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: zhifou
  labels:
    app: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 31200