apiVersion: v1
kind: Service
metadata:
  namespace: zhifou
  # service name 不能叫 kafka
  # https://github.com/wurstmeister/kafka-docker/issues/122
  name: kafka-service
  labels:
    app: kafka-service
spec:
  type: NodePort
  ports:
    - port: 9092
      name: kafka
      targetPort: 9092
      nodePort: 30092
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zhifou
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.13-2.6.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
#              Service 的 cluster Ip
              value: "10.103.116.17"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_BROKER_ID
              value: "1"