apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zhifou-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zhifou-front
  template:
    metadata:
      labels:
        app: zhifou-front
    spec:
      containers:
        - name: zhifou-front
          image: registry.cn-hangzhou.aliyuncs.com/qian0817docker/zhifou-front:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: zhifou-front
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: zhifou-front
