apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zhifou
  name: zhifou-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zhifou-front
  template:
    metadata:
      namespace: zhifou
      labels:
        app: zhifou-front
    spec:
      containers:
        - name: zhifou-front
          image: registry.cn-hangzhou.aliyuncs.com/qian0817docker/zhifou-front:0.0.1
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /
          readinessProbe:
            httpGet:
              port: 80
              path: /
---
apiVersion: v1
kind: Service
metadata:
  namespace: zhifou
  name: zhifou-front
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: zhifou-front
