apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zhifou-question
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zhifou-question
  template:
    metadata:
      labels:
        app: zhifou-question
    spec:
      containers:
        - name: zhifou-question
          image: registry.cn-hangzhou.aliyuncs.com/qian0817docker/zhifou-question:0.0.1
          env:
            - name: CONSUL_HOST
              value: consul
            - name: CONSUL_PORT
              value: "8500"
            - name: CONSUL_CONFIG_FORMAT
              value: yaml

---
apiVersion: v1
kind: Service
metadata:
  name: zhifou-question
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: zhifou-question
