apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: zhifou
  name: zhifou-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zhifou-user
  template:
    metadata:
      namespace: zhifou
      labels:
        app: zhifou-user
    spec:
      containers:
        - name: zhifou-user
          image: registry.cn-hangzhou.aliyuncs.com/qian0817docker/zhifou-user:0.0.1
          env:
            - name: CONSUL_HOST
              value: consul
            - name: CONSUL_PORT
              value: "8500"
            - name: CONSUL_CONFIG_FORMAT
              value: yaml
---
apiVersion: v1
kind: Service
metadata:
  namespace: zhifou
  name: zhifou-user
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: zhifou-user
