apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zhifou
  name: zhifou-follow
data:
  application.yaml: |-
    spring:
      datasource:
        url: jdbc:mysql://mysql:3306/zhifou?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Hongkong&characterEncoding=utf-8
        username: qianlei
        password: 123456
      redis:
        host: redis
      kafka:
        consumer:
          group-id: zhifou
          auto-offset-reset: latest
        bootstrap-servers: kafka:9092
      zipkin:
        base-url: http://zipkin:9411/
        sleuth:
          sampler:
            probability: 1
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zhifou-follow
  namespace: zhifou
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zhifou-follow
  template:
    metadata:
      namespace: zhifou
      labels:
        app: zhifou-follow
    spec:
      containers:
        - name: zhifou-follow
          image: registry.cn-hangzhou.aliyuncs.com/qian0817docker/zhifou-follow:0.0.1
          env:
            - name: CONFIG_NAMESPACE
              value: zhifou
#          volumeMounts:
#            - mountPath: /etc/config
#              name: config
#              readOnly: true
#      volumes:
#        - name: config
#          configMap:
#            name: zhifou-follow
---
apiVersion: v1
kind: Service
metadata:
  name: zhifou-follow
  namespace: zhifou
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: zhifou-follow
