apiVersion: v1
kind: ConfigMap
metadata:
  namespace: zhifou
  name:  zhifou-question
data:
  application.yaml: |-
    spring:
      datasource:
        url: jdbc:mysql://mysql:3306/zhifou?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Hongkong&characterEncoding=utf-8
        username: qianlei
        password: 123456
      redis:
        host: redis
      kafka:
        consumer:
          group-id: zhifou
          auto-offset-reset: latest
        bootstrap-servers: kafka:9092
      elasticsearch:
        rest:
          uris: http://elasticsearch:9200
      zipkin:
        base-url: http://zipkin:9411/
        sleuth:
          sampler:
            probability: 1
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: zhifou
  name: zhifou-question
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zhifou-question
  template:
    metadata:
      namespace: zhifou
      labels:
        app: zhifou-question
    spec:
      containers:
        - name: zhifou-question
          image: registry.cn-hangzhou.aliyuncs.com/qian0817docker/zhifou-question:0.0.1
          env:
            - name: CONFIG_NAMESPACE
              value: zhifou
---
apiVersion: v1
kind: Service
metadata:
  namespace: zhifou
  name: zhifou-question
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: zhifou-question
