apiVersion: v1
kind: Service
metadata:
  namespace: zhifou
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: zhifou
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: zookeeper:3.6.2
          name: zookeeper
          ports:
            - containerPort: 2181