spring:
  application:
    name: zhifou-follow
  cloud:
    consul:
      host: localhost
      config:
        format: yaml
  config:
    import: consul:localhost:8500
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
#    prometheus:
#      enable: true
    web:
      exposure:
        include: "*"