jwt:
  rsa:
    alias: jwt
    password: 123456
    key-filename: jwt.jks
spring:
  application:
    name: zhifou-user
  cloud:
    kubernetes:
      config:
        enabled: false
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      config:
        format: ${CONSUL_CONFIG_FORMAT}
  config:
    import: consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    #    prometheus:
    #      enable: true
    web:
      exposure:
        include: "*"