name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    working-directory: back
jobs:
  build:
    env:
      username: ${{secrets.ALIYUN_IMAGES_HUB_USER_NAME}}
      password: ${{secrets.ALIYUN_IMAGES_HUB_TOKEN}}
      registry_url: 'registry.cn-hangzhou.aliyuncs.com'
      namespaces: 'qian0817docker'
      image_version: '0.0.1'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Login Docker
      run: echo $password | docker login --username=$username $registry_url --password-stdin

    - name: Build User Server Docker Image
      run: docker build -t $registry_url/$namespaces/zhifou-user:$image_version .\zhifou-user\
    - name: Push User Server Docker Image
      run: docker push $registry_url/$namespaces/zhifou-user:$image_version

    - name: Build Follow Server Docker Image
      run: docker build -t $registry_url/$namespaces/zhifou-follow:$image_version .\zhifou-follow\
    - name: Push Follow Server Docker Image
      run: docker push $registry_url/$namespaces/zhifou-follow:$image_version

    - name: Build Question Server Docker Image
      run: docker build -t $registry_url/$namespaces/zhifou-question:$image_version .\zhifou-question\
    - name: Push Question Server Docker Image
      run: docker push $registry_url/$namespaces/zhifou-question:$image_version

    - name: Build Comment Server Docker Image
      run: docker build -t $registry_url/$namespaces/zhifou-comment:$image_version .\zhifou-comment\
    - name: Push Comment Server Docker Image
      run: docker push $registry_url/$namespaces/zhifou-comment:$image_version