name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    working-directory: back
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build comment Docker Image
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hangzhou.aliyuncs.com'
        namespaces: 'qian0817docker'
        repository_name: 'zhifou-comment'
        user_name: ${{ secrets.ALIYUN_IMAGES_HUB_USER_NAME }}
        password: ${{ secrets.ALIYUN_IMAGES_HUB_TOKEN }}
        image_version: '0.0.1'
        docker_file: './zhifou-comment/'
    - name: Build follow Docker Image
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hangzhou.aliyuncs.com'
        namespaces: 'qian0817docker'
        repository_name: 'zhifou-follow'
        user_name: ${{ secrets.ALIYUN_IMAGES_HUB_USER_NAME }}
        password: ${{ secrets.ALIYUN_IMAGES_HUB_TOKEN }}
        image_version: '0.0.1'
        docker_file: './zhifou-follow/'
    - name: Build question Docker Image
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hangzhou.aliyuncs.com'
        namespaces: 'qian0817docker'
        repository_name: 'zhifou-question'
        user_name: ${{ secrets.ALIYUN_IMAGES_HUB_USER_NAME }}
        password: ${{ secrets.ALIYUN_IMAGES_HUB_TOKEN }}
        image_version: '0.0.1'
        docker_file: './zhifou-question/'
    - name: Build user Docker Image
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'registry.cn-hangzhou.aliyuncs.com'
        namespaces: 'qian0817docker'
        repository_name: 'zhifou-user'
        user_name: ${{ secrets.ALIYUN_IMAGES_HUB_USER_NAME }}
        password: ${{ secrets.ALIYUN_IMAGES_HUB_TOKEN }}
        image_version: '0.0.1'
        docker_file: './zhifou-user/'