# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      username: ${{secrets.ALIYUN_IMAGES_HUB_USER_NAME}}
      password: ${{secrets.ALIYUN_IMAGES_HUB_TOKEN}}
      registry_url: 'registry.cn-hangzhou.aliyuncs.com'
      namespaces: 'qian0817docker'
      image_version: '0.0.1'
    defaults:
      run:
        working-directory: ./front
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm build

      - name: Login Docker
        run: echo $password | docker login --username=$username $registry_url --password-stdin

      - name: Build Front Server Docker Image
        run: docker build -t $registry_url/$namespaces/zhifou-front:$image_version .
      - name: Push Front Server Docker Image
        run: docker push $registry_url/$namespaces/zhifou-front:$image_version